### ISSUE TITLE
Improve styling

### ISSUE THREAD

**Issue by Brakistad** [WebRodent/webrodent.github.io#2]
![image](https://github.com/user-attachments/assets/1de8014c-ea8f-4ef0-8199-c67d5ac7536f)
I think we should have these three products in white text with a rounded rectangular bounding each one individually.
The color coding is a clever way to make the experience more streamlined with the three sections below, so i love that. And we should keep the color coding idea, but maybe have the colors be subtle fades in the edges of their rounded cotnainers/rectangles

**Comment by Ruholt** [comment]
Refactored
